# Generated by Django 3.0.3 on 2020-06-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_class', models.TextField()),
                ('delegue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('cin', models.CharField(default='null', max_length=10)),
                ('tel', models.IntegerField(default=0)),
                ('email', models.CharField(default='null', max_length=25)),
                ('grade', models.TextField()),
                ('address_pro', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.TextField()),
                ('responsable', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.TextField(default='null')),
                ('description', models.TextField(default='null')),
                ('enseignant', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salle_type', models.CharField(choices=[('Amphi', 'Amphi'), ('Salle', 'Salle'), ('A', 'A')], default='', max_length=20)),
                ('num_salle', models.IntegerField()),
                ('seance', models.TimeField(max_length=150)),
                ('date', models.DateField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_fichier', models.FileField(upload_to='file')),
                ('rc_desc', models.TextField(blank='true', default='null')),
                ('classe', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Classe')),
                ('enseignant', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Enseignant')),
                ('filiere', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Pfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=50)),
                ('cahier_charg', models.FileField(upload_to='file')),
                ('delai', models.DateField(max_length=100)),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Enseignant')),
                ('filiere', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_module', models.TextField()),
                ('porcentage', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Classe')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Module'),
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Classe')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Matiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Salle')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('cin', models.CharField(default='null', max_length=10)),
                ('tel', models.IntegerField(default=0)),
                ('email', models.CharField(default='null', max_length=25)),
                ('cne', models.CharField(max_length=10)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=25)),
                ('adr_act', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=15)),
                ('ville', models.CharField(max_length=25)),
                ('photo', models.ImageField(upload_to='file')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Classe')),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='filiere',
            field=models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Filiere'),
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.FileField(blank='true', upload_to='file')),
                ('cours_type', models.CharField(choices=[('CM', 'CM'), ('TD', 'TD'), ('TP', 'TP')], default='', max_length=20)),
                ('groupe', models.CharField(blank='true', max_length=20)),
                ('classe', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Classe')),
                ('filiere', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Matiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Salle')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.Filiere'),
        ),
    ]
