# Generated by Django 3.1.6 on 2021-03-04 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioncours', '0002_auto_20210304_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank='True'),
        ),
    ]
