# Generated by Django 3.1.6 on 2021-03-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncours', '0004_auto_20210307_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='seance',
        ),
    ]
