# Generated by Django 3.1.6 on 2021-03-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncours', '0006_auto_20210307_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='A_salle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emploi',
            name='A_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emploi',
            name='B_salle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emploi',
            name='B_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emploi',
            name='C_salle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emploi',
            name='C_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emploi',
            name='D_salle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emploi',
            name='D_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
