# Generated by Django 3.1.6 on 2021-03-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncours', '0007_auto_20210307_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploi',
            name='A',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='A_salle',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='A_type',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='B',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='B_salle',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='B_type',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='C',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='C_salle',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='C_type',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='D',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='D_salle',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='D_type',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='jour',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='name',
        ),
        migrations.AddField(
            model_name='emploi',
            name='cours_type',
            field=models.CharField(blank='True', choices=[('CM', 'CM'), ('TD1', 'TD1'), ('TD2', 'TD2'), ('TP1', 'TP1'), ('TP2', 'TP2'), ('TP3', 'TP3')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emploi',
            name='matiere',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestioncours.matiere'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='salle',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestioncours.salle'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestioncours.classe'),
        ),
    ]
