# Generated by Django 3.1.6 on 2021-03-20 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncours', '0010_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='classe',
            field=models.ForeignKey(blank='true', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestioncours.classe'),
        ),
    ]
