# Generated by Django 3.1.6 on 2021-03-31 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncours', '0011_matiere_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestioncours.enseignant'),
        ),
    ]
