# Generated by Django 3.1.6 on 2021-03-04 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioncours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='adr_act',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cne',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(default='null', max_length=25),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank='True', upload_to='file'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='ville',
            field=models.CharField(default='null', max_length=25),
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('A', models.CharField(max_length=100)),
                ('B', models.CharField(max_length=100)),
                ('C', models.CharField(max_length=100)),
                ('D', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncours.classe')),
            ],
        ),
    ]
